### ISSUE TITLE
billboard.py should be updated

### ISSUE THREAD

**Issue by guoguo12** [brycematsuda/simply-billboard#3]
Hey Bryce! Just a heads up: the version of billboard.py you're using is out of date, and no longer works (because Billboard.com changed their CSS). You should update it ASAP. `pip install billboard.py --upgrade` will do the trick.

**Comment by brycematsuda** [comment]
Thanks for the heads up! I did see the update the other day, but I got busy with other things.

**Comment by guoguo12** [comment]
:+1:
